name: Auto Update Template List

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate template list
        run: |
          echo '{ "templates": [' > templates.json
          for dir in templates/*/ ; do
            name=$(basename "$dir")
            echo "  {\"name\": \"${name}\", \"path\": \"${dir%/}\"}," >> templates.json
          done
          sed -i '$ s/,$//' templates.json
          echo ']}' >> templates.json

      - name: Commit & push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add templates.json
          git commit -m "Auto update templates list"
          git push
